### ISSUE TITLE
Uncaught runtime errors

### ISSUE THREAD

**Issue by pwrliang** [DalsuChoi/Waffle#1]
Dear Waffle authors, I have deployed Waffle on my machine and tried to explore it.

I typed w_time = 0.5, w_memory = 0.5, regrid=2 on the "User Preference" and clicked the set button.

It looks like the server received requests from the node server:
![image](https://github.com/DalsuChoi/Waffle/assets/14839342/559c7e24-d513-4159-80f8-a10b3c1b821e)

But the node server raised the following error.

<img width="605" alt="image" src="https://github.com/DalsuChoi/Waffle/assets/14839342/0cf0bfc1-2484-4a0c-b5a9-c861059ce67c">

Server
```
./Waffle ~/Datasets/OSM2015_road-network.small 20000
```

These are my settings:

```
npm version: 9.6.7
node version: v18.17.1
gcc version: 9.4.0
```

How can I troubleshoot this?

**Comment by DalsuChoi** [comment]
I am sorry for the late answer. I didn't recognize that this issue has opened.
I cannot check it right now, but let me check it as soon as possible.
Thank you.

**Comment by DalsuChoi** [comment]
At my first glance, it is not an expected behavior to click 'set' button in the interface multiple times.
I would like to know if it is related to this issue.
Thank you.
